### PR TITLE
Remove dependency on BouncyCastle ASN.1

### PR DESCRIPTION
**Pull request by hierynomus**
Can be merged once asn-one has been released.

### CODE REVIEW

**Comment by hierynomus** [comment]
TODO left:
[] Make BC optional
[] Ensure no BC references in anything but SecurityProvider package.

**Comment by krivanekm-javlin** [comment]
I've tested it and it looks like BC is no longer required and all our tests have passed. However, I don't think we use neither Spnego nor NTLM authentication in our test environment.

If I understand it correctly, BC is now only required if I explicitly call `SmbConfig.Builder.withSecurityProvider(new BCSecurityProvider())`, it that correct?

**Comment by hierynomus** [comment]
Yes, correct

**Comment by krivanekm-javlin** [comment]
Just a minor comment, I've noticed that asn-one uses "com.hierynomus.asn-one" as the group ID, but smbj and sshj use "com.hierynomus". Is that intentional?

**Comment by hierynomus** [comment]
> Just a minor comment, I've noticed that asn-one uses "com.hierynomus.asn-one" as the group ID, but smbj and sshj use "com.hierynomus". Is that intentional?

Totally unintentional! Well spotted. I'll move asn-one a level up.

**Pull request merged**
