### PR TITLE
Rework exception handling

### PR DESCRIPTION
**Pull request by hierynomus**
Rework the Exception handling strategies, as requested in issue #148.

### CODE REVIEW

**Comment by kilokahn** [comment]
@hierynomus - While we are at it, can we consider `com.hierynomus.smbj.connection.Connection#close()` to throw `IOException` rather than `Exception`? 
Thanks.

**Comment by jansohn** [comment]
Any plans to merge this?

**Comment by hierynomus** [comment]
Not in its current form. I need to re-think this and see which parts are useful to change.

**Comment by hierynomus** [comment]
If we ever want to do this, need to reimplemnt this.

**Pull request closed without merging**
