### PR TITLE
Add setSecurityInformation

### PR DESCRIPTION
**Pull request by pepijnve**

### CODE REVIEW

**Comment by hierynomus** [comment]
Will review later today, thanks!

2017-06-12 11:07 GMT+02:00 Pepijn Van Eeckhoudt <notifications@github.com>:

**Comment by hierynomus** [comment]
Overall looks good I think. Diff is a bit hard to read in some places. It would be good to have some additional (unit) tests, what do you think?

**Comment by pepijnve** [comment]
What would you want covered by unit tests? Marshalling and unmarshalling of security descriptors? I can make some basic file DACL examples. No idea how to concoct a complex SACL though.

**Comment by pepijnve** [comment]
Added a method to parse SID literals (mainly for convenience in unit tests)
Added basic SD unit tests for marshalling and unmarshalling

**Comment by pepijnve** [comment]
@hierynomus are the unit tests sufficient or is there anything else that needs to be covered?

**Comment by hierynomus** [comment]
Haven't had a look yet, will do momentarily!

**Pull request merged**
