### PR TITLE
Set basic file info

### PR DESCRIPTION
**Pull request by sopak**
Added support for setBasicFileInformation
We need to be able setup attributes, creationTime etc.

### CODE REVIEW

**Comment by yin19941005** [comment]
Hi @sopak ,

I had implemented `setInfoCommon` on #52 ([code in here](https://github.com/hierynomus/smbj/pull/52/files#diff-cca6d04c0249357b1f90fee34eeea7cbR585)) and it seems it would also works with set basic file info.

We can simply rewrite the setBasicFileInformation with the setInfoCommon like this : 
```
public void setBasicFileInformation(
        SMB2FileId fileId,
        Date creationTime,
        Date lastAccessTime,
        Date lastWriteTime,
        Date changeTime,
        long fileAttributes)
        throws SMBApiException, TransportException {

        try {
            byte[] basicInfo = FileInformationFactory.getFileBasicInfo(
                creationTime,
                lastAccessTime,
                lastWriteTime,
                changeTime,
                fileAttributes
            );

            setInfoCommon(fileId,
                SMB2SetInfoRequest.SMB2InfoType.SMB2_0_INFO_FILE,
                null,
                FileInformationClass.FileBasicInformation,
                basicInfo);

        } catch (Buffer.BufferException e) {
            throw new SMBRuntimeException(e);
        }
        
    }
```
I had tested some for it and it works fine. I think we can integrate them, what do you think about it?

**Comment by sopak** [comment]
Sure we can.
It would be good add another method setBasicFileInformation directly for String path.

@hierynomus  what will be the best way how to merge it?

**Comment by hierynomus** [comment]
I was looking at the PRs right now :). Let me merge #49 and #52 first, then you can pull master into this branch.

**Comment by yin19941005** [comment]
Hi @sopak ,

Sure, I will try to add it later. Currently, I am implementing both the String path and the SMB2FileId fileId to set the just one of the fileBasicInformation. I am trying to create a new enum class and a new factory to create the byte array for just set one attribute. I will try to make a pull request for them after #49 and #52 got merged. 

@hierynomus ,
Thanks a lot!

**Comment by pepijnve** [comment]
@sopak You might want to rebase this on PR #59 (if it gets merged). That provides preliminary support for SetInfo requests and includes a FileBasicInformation class.
I also added FileTime constants in FileBasicInformation for the 'don't set' and 'don't update' special values. If you use those you can get rid of the FileBasicInformationEnum.

**Comment by sopak** [comment]
@hierynomus if possible merge #59 first.
I will rebase and modify this PR #50 afterwards.

**Comment by hierynomus** [comment]
Yes, currently looking at that :)

BTW: @sopak @pepijnve @yin19941005 Thanks for all the PRs! Really appreciate your contributions so far! I have a hard time keeping up with 'regular' work in between 😁

**Comment by sopak** [comment]
I believe this is now ready to be merged.

**Comment by pepijnve** [comment]
@sopak you might want to rebase and squash this PR to master. Bit messy now.

**Comment by sopak** [comment]
@pepijnve I may try to do it.

**Comment by hierynomus** [comment]
I think something went wrong, I see the big switch statement now, I thought that was gone with the new FileInformation stuff :)

**Comment by sopak** [comment]
I will create another branch and cleaner PR.

**Comment by sopak** [comment]
This PR is closed with a succestor PR #65

**Pull request closed without merging**
