### PR TITLE
SMB2 Signature and other enhancements

### PR DESCRIPTION
**Pull request by sbellan**
Hi Jeroen,

Finally had some time to contribute some enhancements we had done upstream. Looks like lots of changes on your side also. Spent quite some quite time to merge/rebase. Please review the pull request,

- Support SMB2 Signatures
- New NT error codes
- listDirectory to get the full list

Looks like with some refactoring of the SMB2WriteRequest from byte array to streaming ByteChunkProvider, is causing issues with the signature generation, Since to compute signature we need write the packet into a buffer first. Since we are using streams now, it is tricky, need to find out the proper way.

### CODE REVIEW

**Comment by hierynomus** [comment]
Hi @sbellan! As discussed in #7 I'll merge the PR from @ckherrmann. I would like to ask you to submit the other changes you have in a separate PR.
Thanks for the contribution :)

**Comment by hierynomus** [comment]
@sbellan Do you have some time to submit the other changes as a separate PR?

**Comment by sbellan** [comment]
Sorry, got really busy. Will do in the next couple of days.

**Comment by hierynomus** [comment]
@sbellan Any idea if you're able to do this before Friday? This Friday I want to spend some time on SMBJ and try to release a new version with all the new features in there, would be great to have your fixes in there also.

**Pull request closed without merging**
