### PR TITLE
throw error when state is not DFSPath

### PR DESCRIPTION
**Pull request by cliviu**

### CODE REVIEW

**Comment by hierynomus** [comment]
Can you explain? See the javadoc above...

**Comment by cliviu** [comment]
step14 indicates an error. why should be an error indicated when the path is a DFS path ? 
The problem that I had is that I have a DFS mount which contains a link to another smbv2 share, perfectly legal under windows.
The test always failed when trying to list the contents of the smbv2 share because it detected that the path is a DFS path and jumped to step 14 which is an error. Can you please explain, I'm not sure if I understood right,

**Comment by cliviu** [comment]
Maybe there is some other way to solve this problem, I've just done the simplest change so that the test works.

**Comment by pepijnve** [comment]
@cliviu DFSPathResolver implements the DFS path resolution algorithm described in [[MS-DFSC]](https://msdn.microsoft.com/en-us/library/cc227028.aspx). There might very well be a mistake in there somewhere, but flipping the yes/no branch to solve one particular case doesn't seem like the best way to fix this. Perhaps you could describe the configuration in which things are not working for you along with a small code snippet so that someone can try and reproduce this?

**Comment by cliviu** [comment]
By the way, in DFSPathResolver, line 348 why is the port 451 hardcoded ? (marked with TODO) What does this port represent ? 445 is the smb port usually, isn't it ?

**Comment by hierynomus** [comment]
Thanks, I just removed the hardcoded port, missed that.

**Comment by hierynomus** [comment]
And @pepijnve is right, that's why I pointed at the JavaDoc. I might have very well made a mistake (it is a complex spec). But flipping boolean logic without any reasoning is the wrong way of fixing things.

I would prefer a way to set it up (See DFSIntegrationSpec) and having a test that ensures we don't break anything

**Comment by cliviu** [comment]
sure, I will take a look at the specs, see if I can find something. Is pretty  difficult to provide a test that reproduces the problem because this should be an integration test, But I will give you the test program and the directory structure.

**Comment by hierynomus** [comment]
If you can give a step by step process on what to setup on a windows box
(or a powershell script), it should be easy enough to write an integration
test to match


2017-09-05 14:03 GMT+02:00 Liviu Carausu <notifications@github.com>:

**Comment by cliviu** [comment]
Hi, here is the configuration. There is a DFS server  "dfs.server" with a share "DFS_Share". direct under "DFS_Share" there is a directory called "smb" which is a link to anothe smbv2 Share on a different server

SmbConfig config = SmbConfig.builder().   withMultiProtocolNegotiate(true).withSigningRequired(true).withDfsEnabled(true).build()

       SMBClient client = new SMBClient(config);

        Connection connection = client.connect("dfs.server");

        Session authenticate = connection.authenticate(new AuthenticationContext("user", "pwd".toCharArray(), null));

        DiskShare connectShare = (DiskShare)authenticate.connectShare("DFS_Share");                   

        Directory openDirectory = connectShare.openDirectory("smb", EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null);

        List<FileIdBothDirectoryInformation> list = openDirectory.list();

        for(FileIdBothDirectoryInformation fileInfo : list) {
            //list info
        }

**Comment by cliviu** [comment]
com.hierynomus.msdfsc.DFSException: DFS request failed for path DFSPath{[anotherserver, smb2test]}
	at com.hierynomus.smbj.share.DFSPathResolver.step14(DFSPathResolver.java:336)
	at com.hierynomus.smbj.share.DFSPathResolver.step6(DFSPathResolver.java:205)
	at com.hierynomus.smbj.share.DFSPathResolver.step5(DFSPathResolver.java:156)
	at com.hierynomus.smbj.share.DFSPathResolver.step2(DFSPathResolver.java:93)
	at com.hierynomus.smbj.share.DFSPathResolver.step11(DFSPathResolver.java:304)
	at com.hierynomus.smbj.share.DFSPathResolver.step4(DFSPathResolver.java:131)
	at com.hierynomus.smbj.share.DFSPathResolver.step7(DFSPathResolver.java:220)
	at com.hierynomus.smbj.share.DFSPathResolver.step6(DFSPathResolver.java:198)
	at com.hierynomus.smbj.share.DFSPathResolver.step5(DFSPathResolver.java:156)
	at com.hierynomus.smbj.share.DFSPathResolver.step2(DFSPathResolver.java:93)
	at com.hierynomus.smbj.share.DFSPathResolver.step1(DFSPathResolver.java:76)
	at com.hierynomus.smbj.share.DFSPathResolver.resolve(DFSPathResolver.java:62)
	at com.hierynomus.smbj.share.DFSDiskShare.open(DFSDiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:78)
	at integration.DfsTest.main(DfsTest.java:58)
Exception in thread "main" com.hierynomus.mssmb2.SMBApiException: STATUS_PATH_NOT_COVERED(3221226071/3221226071): Cannot resolve DFS path for smb
	at com.hierynomus.smbj.share.DFSDiskShare.open(DFSDiskShare.java:73)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:78)
	at integration.DfsTest.main(DfsTest.java:58)

**Comment by cliviu** [comment]
for me is questionable if in DFSPathResolver.step11 `state.isDFSPath = true;` is correct. 

I think we are talking now about another path which is given to the step 2

https://msdn.microsoft.com/en-us/library/cc227028.asp

> step 11 : [interlink] Replace the portion of the path that matches the DFSPathPrefix of the ReferralCache entry with TargetHint. For example, if the path is \MyDomain\MyDfs\MyLink\MyDir and the referral entry contains \MyDomain\MyDfs\MyLink with a DFS target path of \someserver\someshare\somepath, the effective path becomes \someserver\someshare\somepath\MyDir. Go to step 2.

**Comment by cliviu** [comment]
Does it make sense  ?

**Comment by cliviu** [comment]
@hierynomus , have you got a chance to look into this  ?

**Comment by cliviu** [comment]
@hierynomus ?

**Comment by hierynomus** [comment]
The main question is, how thoroughly did you test the change?

I have had no time to test the proposed change.

**Comment by cliviu** [comment]
Hi, just wanted to know if the change is completely rejected or if you had no time to look at it. 
I have tested with my test case that I described. I think it will make sense to take the one line change that I have made in your integration tests, see if is working, this will still be a good sign :-). Thanks !

**Comment by cliviu** [comment]
I think it may be a good fix for https://github.com/hierynomus/smbj/issues/152  also

**Comment by pepijnve** [comment]
While I was trying to reproduce the issue reported in #212 I think I found the root cause for this. At https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/msdfsc/ReferralCache.java#L120 there's a TODO that's rather crucial. At the moment the interlink flag is sometimes incorrectly set to true causing a recursive DFS referral lookup. When the target server is not a DFS server you get an error. I'll make a new PR to fix that TODO.

**Comment by hierynomus** [comment]
@cliviu Can you check whether it is now fixed (without this PR)?

**Comment by cliviu** [comment]
hi, @hierynomus , my issue is fixed with https://github.com/hierynomus/smbj/pull/218 , my PR is not necessary anymore, you can remove it

**Pull request closed without merging**
