### PR TITLE
Added helper methods for writing files to share

### PR DESCRIPTION
**Pull request by mtamassia**
Added 3 helper methods to DiskShare to facilitate uploads:
 public int write(String path, InputStream is, boolean overwrite)
 public int write(String path, java.io.File localFile, boolean overwrite)
 public int write(String path, java.io.File localFile)

### CODE REVIEW

**Comment by mtamassia** [comment]
Apologies for all the Line Break changes triggering the diff to flag all lines. I only added 53 lines of code with the 3 functions...

**Comment by hierynomus** [comment]
Hi @mtamassia,

As it is, I will not accept the PR in this state. This messes up the entire file.

Furthermore, I do not agree that these functions belong in the `DiskShare`. I would be ok-ish with Adding a `SmbFiles.copy(File source, DiskShare dest, String destPath)` or something like that.

**Comment by mtamassia** [comment]
No problem @hierynomus. 

I will change git line endings behavior on my end as well so the future PRs are clean.

I can add a static SmbFiles.copy method. Would you want that into its own SmbFiles class inside main.java.com.hierynomus.smbj, inside main.java.com.hierynomus.smbj.share or would you want somewhere else?

**Comment by hierynomus** [comment]
First idea would be com.hierynomus.smbj.utils

Op 14 jul. 2017 22:03 schreef "mtamassia" <notifications@github.com>:

**Comment by mtamassia** [comment]
Closing this PR as I sent you a new one.

**Pull request closed without merging**
