### PR TITLE
Copy issue 175

### PR DESCRIPTION
**Pull request by JozefDropco**
Hi, 
I tried to implement server-side copy of file. I dont know where you would like to place those files as it creates new concept into your code (looping and reacting on response within your code). I think there is a possibility to add progress listener.

### CODE REVIEW

**Comment by tothed** [comment]
Hello.

Is this going to be added ?
Streaming file data on the same DFS seems to me as a good reason for adding it.
Also, SMB 2 supports this functionality so I see it as a natural addition to API

Best
Ed

**Comment by pepijnve** [comment]
@JozefDropco I've made some simplifications to the code and some robustness improvements based on testing this with an EMC Isilon server at https://github.com/JozefDropco/smbj/pull/1.

**Comment by hierynomus** [comment]
Ill try to have a look somewhere next week. I also started refactoring the original pr, will rebase based on your changes @pepijnve. Thanks for testing it!

**Comment by felipecaparelli** [comment]
@hierynomus this functionality is very important to SMB... do you have any doubts about the quality of this code?

**Comment by hierynomus** [comment]
@felipecaparelli Yes :) See the PR checks and merge conflicts that are present.
Merging is not straightforward anymore. Furthermore I want to see whether we can simplify the API a bit. However I'm pretty short on time due to moving between houses...

**Comment by hierynomus** [comment]
Superseded by #366

**Pull request closed without merging**
