### PR TITLE
Tried adding reproduction testcase for #603

### PR DESCRIPTION
**Pull request by hierynomus**
@nddipiazza I've tried adding a reproduction testcase to the DFS integration test spec, but cannot seem to reproduce your issue, can you have a look?

### CODE REVIEW

**Comment by nddipiazza** [comment]
HI I think it only happens when testing against windows server.

**Comment by hierynomus** [comment]
Hmm... I don't have a windows server lying around unfortunately, do you have an ability to debug this issue and see where this is coming from?

**Comment by hierynomus** [comment]
@pepijnve Do you have an ability to see where this is coming from?

**Comment by nddipiazza** [comment]
We should sync up sometime. I can probably get you access to a windows VM that you can use for your integration tests.
I can debug and try to find the culprit when I get some time. I've got a bunch of high priority stuff on plate right now, next week probably earliest I can realistically take a look.

**Comment by nddipiazza** [comment]
i took this branch and added the fix for it here: https://github.com/hierynomus/smbj/pull/610
updated the integration test as well

**Comment by hierynomus** [comment]
Superseeded by #610

**Pull request closed without merging**
