### PR TITLE
Stress Test Documentaion

### PR DESCRIPTION
**Pull request by NinjaChris16**
Added some information on stress test applications for SMB. The stress test file contains information on stress test applications and links to their websites/manuals. A link to the file was added to the bottom of the README.

### CODE REVIEW

**Comment by NinjaChris16** [comment]
@codyswanson4 Let me know your thoughts.

**Comment by hierynomus** [comment]
@NinjaChris16 What is this for? Can you give a bit more background. Your added documentation refers mostly to SMB servers, which is not what SMBJ is.

**Comment by NinjaChris16** [comment]
@hierynomus This was just some documentation and information on stress test resources for SMB and SMBJ implementations. I am working with a client who just started using the SMBJ library and needed some information on how to stress test their implementation. Seeing as there was not any aggregated information regarding this subject, I resolved to put it here for others with the same question.

**Comment by pepijnve** [comment]
No offences, but I don't think this is very relevant for the SMBJ project since this is all about using a Samba based client to stress test server implementations.
Should this PR be closed?

**Comment by hierynomus** [comment]
That's why I first asked the question indeed, but I had the same feeling. I agree this is irrelevant, unless @NinjaChris16 and @codyswanson4 want to add an SmbServer implementation

**Pull request closed without merging**
