### PR TITLE
Remote copy take 2

### PR DESCRIPTION
**Pull request by pepijnve**
This is a rebased version of PR #294. Adds remote file copy support.

### CODE REVIEW

**Comment by pepijnve** [comment]
@hierynomus I've further simplified and reduced the PR initially created by @JozefDropco down to the absolute minimum. Code is now pretty straightforward I think.

**Comment by hierynomus** [comment]
Code looks way better already indeed.

Two things:
1. Codacy isn't happy (haven't checked why)
2. The IntegrationTest will not run out of the box, as it does not upload the files to the host before testing.

**Comment by pepijnve** [comment]
Codacy warning fixed.
Integration test now generates the source file itself.

**Comment by pepijnve** [comment]
Note that in the old version I had added a special case for some server that responded in a non-standard way. That's what the
> Handle STATUS_INVALID_PARAMETER without a SRV_COPYCHUNK_RESPONSE
commit was about.

I can't remember which server that was or when this happened exactly, so I've omitted the code related to that for the time being.

**Comment by felipecaparelli** [comment]
Thank you so much @hierynomus and @pepijnve! This feature provides great performance for softwares using SMB protocol.

**Comment by felipecaparelli** [comment]
@hierynomus Do you will update the project version in the maven repository after this release?

**Comment by hierynomus** [comment]
@felipecaparelli Version 0.8.0 has been pushed out to Maven central.

**Pull request merged**
