### PR TITLE
Correctly read error responses (Fixes #112 #94)

### LINKED ISSUE #112: Non-successful response would fail signature verification.
The signature is not generated with the entire message if the response status is not STATUS_SUCCESS for at least a few message type (SMB2ReadResposne and SMB2QueryDirectoryResponse)

The packet.getMessageEndPos()'s return value in PacketSignatory#verify is off.

This issue can be reproduced by requiring signature in the SmbConfig and read from an empty file.

### PR DESCRIPTION
**Pull request by hierynomus**

### CODE REVIEW

**Comment by hierynomus** [comment]
@pepijnve @bli-r7 @Pernicies Could you verify whether this fixes signature validation. My initial tests show it should, but would be great to have some additional checks.

**Comment by Pernicies** [comment]
I can confirm that the signature validation is now working as expected in my application.

**Comment by pepijnve** [comment]
Change itself looks good. I'm not at work for two weeks. I'll run some tests against our NetApp servers when I get back. Those were causing signature verification errors during testing.

**Comment by bli-r7** [comment]
The fix worked for me as well

**Pull request merged**
